<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> SSL_read() returning SSL_ERROR_SYSCALL with errno 11EAGAIN
   </TITLE>
   <LINK REL="Index" HREF="https://mta.openssl.org/pipermail/openssl-users/2019-May/index.html" >
   <LINK REL="made" HREF="mailto:openssl-users%40openssl.org?Subject=Re%3A%20SSL_read%28%29%20returning%20SSL_ERROR_SYSCALL%20with%20errno%2011EAGAIN&In-Reply-To=%3C4a6efadd-594b-ca1e-3f67-998ffd3a069a%40openssl.org%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="010367.html">
   <LINK REL="Next"  HREF="010374.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>SSL_read() returning SSL_ERROR_SYSCALL with errno 11EAGAIN</H1>
    <B>Matt Caswell</B> 
    <A HREF="mailto:openssl-users%40openssl.org?Subject=Re%3A%20SSL_read%28%29%20returning%20SSL_ERROR_SYSCALL%20with%20errno%2011EAGAIN&In-Reply-To=%3C4a6efadd-594b-ca1e-3f67-998ffd3a069a%40openssl.org%3E"
       TITLE="SSL_read() returning SSL_ERROR_SYSCALL with errno 11EAGAIN">matt at openssl.org
       </A><BR>
    <I>Wed May  1 07:42:06 UTC 2019</I>
    <P><UL>
        <LI>Previous message: <A HREF="010367.html">SSL_read() returning SSL_ERROR_SYSCALL with errno 11EAGAIN
</A></li>
        <LI>Next message: <A HREF="010374.html">SSL_read() returning SSL_ERROR_SYSCALL with errno 11EAGAIN
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#10368">[ date ]</a>
              <a href="thread.html#10368">[ thread ]</a>
              <a href="subject.html#10368">[ subject ]</a>
              <a href="author.html#10368">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>

On 30/04/2019 23:37, Viktor Dukhovni wrote:
&gt;<i> On Tue, Apr 30, 2019 at 03:23:23PM -0700, Erik Forsberg wrote:
</I>&gt;<i> 
</I>&gt;&gt;&gt;<i> Is the handshake explicit, or does the application just call
</I>&gt;&gt;&gt;<i> SSL_read(), with OpenSSL performing the handshake as needed?
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> I occasionally (somewhat rarely) see the issue mentioned by the OP.
</I>&gt;&gt;<i> Ignoring the error, or mapping it and do what WANT_READ/WANT_WRITE
</I>&gt;&gt;<i> does effectively hides the issue and connection works fine. I predominantly
</I>&gt;&gt;<i> run on Solaris 11. In my case, I open the socket myself, set non-blocking
</I>&gt;&gt;<i> mode and associates with an SSL object using SS_set_fd().
</I>&gt;&gt;<i> The initial handshake is done explicitly.
</I>&gt;<i> 
</I>&gt;<i> Recoverable errors should not result in SSL_ERROR_SYSCALL.  This
</I>&gt;<i> feels like a bug.  I'd like to hear from Matt Caswell on this one.
</I>&gt;<i> Perhaps someone should open an issue on Github...
</I>&gt;<i> 
</I>
SSL_ERROR_SYSCALL should not be raised as result of a recoverable error. This
should always be considered fatal. If you are getting this but errno says EAGAIN
then a number of possibilities spring to mind:

1) If a fatal error has occurred SSL_get_error() checks to see if there is an
error on the OpenSSL error queue. If there is it returns SSL_ERROR_SSL (unless
the error type is ERR_LIB_SYS). If there is no error at all, but libssl doesn't
think the error is recoverable then it will return SSL_ERROR_SYSCALL by default.
It is possible that libssl has encountered some non-syscall related error but
neglected to push an error onto the error queue. Thus the return value
incorrectly indicates SSL_ERROR_SYSCALL when it should have been SSL_ERROR_SSL.
This would be an OpenSSL bug - but quite tricky to find since we'd have to
locate the spot where no error is being pushed...but because there is no error
we don't have a lot to go on!

2) A second possibility is that it really was a syscall that failed but
something (either in libssl or possibly in application code) made some
subsequent syscall that changed errno in the meantime. If that &quot;something&quot; was
in libssl then that's probably also a libssl bug. (Also quite tricky to track down)

3) A third possibility is that it really is a retryable error but libssl failed
to properly set its state to note that. I think this is quite a lot less likely
than (1) or (2) but would also be a libssl bug.


So my guess is, except in the case where the application itself has accidentally
changed errno, this most likely indicates an openssl bug. The safest thing to do
in such circumstances is to treat this as a fatal error. It is very unwise to
retry a connection where the library has indicated a fatal error (e.g. see
CVE-2019-1559)

What OpenSSL version is this?

Matt
</PRE>



<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="010367.html">SSL_read() returning SSL_ERROR_SYSCALL with errno 11EAGAIN
</A></li>
	<LI>Next message: <A HREF="010374.html">SSL_read() returning SSL_ERROR_SYSCALL with errno 11EAGAIN
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#10368">[ date ]</a>
              <a href="thread.html#10368">[ thread ]</a>
              <a href="subject.html#10368">[ subject ]</a>
              <a href="author.html#10368">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="../../../mailman/listinfo/openssl-users.html">More information about the openssl-users
mailing list</a><br>
</body></html>
